### ISSUE TITLE
Update UI when card is removed

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#5]
When the card is removed, the app should returns back to the welcome screen with the msg 'Please insert card into your smart card reader [...]'
The app state should be reset to default

**Comment by Tech-Aware** [comment]
Well, by a double instanciation of CardConnector in the controller, then it's a little bit difficult for me to manage it dynamically. Then in recents commit where i updated some files, i purpose a manual solution that permite refresh the start_setup frame. Unfortunately, i actually dont found way to solve the double apparition of popup when card is removed, due to double instanciation. Let me know if this solution is well for you  ?

**Comment by Tech-Aware** [comment]
> When the card is removed, the app should returns back to the welcome screen with the msg 'Please insert card into your smart card reader [...]'
> The app state should be reset to default

Pls, check the satochip_utils_verdion_0.4.1 and close this issues if it's solved for you. Thanks
